### ISSUE TITLE
Can't update to 1.0.1

### ISSUE THREAD

**Issue by EmJotGeh** [stjosh/auto_groups#26]
it's not possible to update 1.0.1

"Es ist ein Fehler bei der Anfrage aufgetreten. Es kann nicht fortgefahren werden.
Die App konnte nicht aktualisiert werden."

Nextcloud 18.0.3 - Postgres DB

**Comment by JeanLafon** [comment]
Hi, about the same.
I've got this :
"**Extracted app auto_groups has more than 1 folder**".

**Comment by stjosh** [comment]
Yup, can reproduce. I‘ll try to fix it tomorrow. Sorry for the inconvenience!

**Comment by stjosh** [comment]
Okay, it's definitely an error in my release process. Definitely time to implement #9 . I'll provide a working version tomorrow.

**Comment by stjosh** [comment]
I have published v1.0.2 which should fix this issue. @EmJotGeh @JeanLafon could you please confirm that the update is working now? Sorry again for the inconvenience and many thanks for using my App!

**Comment by JeanLafon** [comment]
Yes.
I coul'd install the app.
I'll see tomorrow the way it works.
Thanks.

**Comment by EmJotGeh** [comment]
Yes, thank you this works perfect! Really nice app :-) thx

**Comment by stjosh** [comment]
Many thanks for your feedback! I‘m therefore closing this issue now. Should anything not work as expected from a functional perspective, feel free to open a new issue.
