### ISSUE TITLE
Group override after changing group assignments of an existing user

### ISSUE THREAD

**Issue by cal940** [stjosh/auto_groups#43]
Hello,

I really like this app, but I have a small problem with the fact, that the app removes an existing user from the default group(s) if the user is already in one of the override groups.

It would be nice, if there would be an option for the admin, to deactivate this.

I personally use this app, only to automatically add a new user to a default group at the user creation. For existing users (after changing group assignments), this feature is a bit irritating. Especially if you don’t want to remove the user from the default group(s).

**Comment by stjosh** [comment]
Hi @cal940 

Thanks for getting in touch - I‘m reslly glad you like the app! Also, thanks for suggesting an enhancement.

However, I think I don‘t really understand your use-case: The very idea of Override Groups is that users in any of those groups cannot be member of the Auto Group(s) at the same time. You are saying

> I personally use this app, only to automatically add a new user to a default group at the user creation.

So I‘m not sure why you are configuring override groups? Why don‘t you simply leave the Override Groups empty? Or am I missing an aspect of your use-case?

**Comment by cal940** [comment]
Hi @stjosh

for better understanding an example:

- default group: **camp organization**
- override groups: **subcamp1, subcamp2**

## Group Definitions:

 - **camp organization:** access to camp organization folders (no access to internal subcamp folders) 

- **subcamp1:** access to internal subcamp1 folder

- **subcamp2:** access to internal subcamp2 folder

The camp organization is divided into different divisions (e.g. **security**, **public relations (pr)**, **infrastructure**, **IT**, **content**, **catering**). Each division has a group admin with access to the members of their division. The **camp organization** group should hold the users from all divisions

Also each sub camp group should have a group admin with access to the members of the sub camp. The group admins and members of the sub camps should have no access to the camp organization or their divisions.

## Summary:

The problem here is, that there are users with positions in the sub camps and in the camp organization who should have access to the files of the sub camps and the camp organization. The ”default group” app this would be no problem, but the app only works for NC >=12.x and NC for the camp uses NC 18.

**Comment by stjosh** [comment]
Wow, sounds complicated. 😄 But I think I am getting the point now. The primary use-case I have intended the app for was "I want to make sure that all users are always included in one/multiple group(s), except users in one of the override groups (e.g., external users, machine accounts, ...)" Very similar purpose like the group_everyone app in that sense.

Your use-case is more like "When I _create_ a user, I wanna make sure he's in the Auto Group unless I specify a more specific group." But the app shall only be active on creation, and not on group modification later on.

Is this understanding correct?

Should be fairly easy to implement I guess. I will probably also add a checkbox to opt out of the behavior that lets the app prevent deletion of the auto / override groups.

**Comment by cal940** [comment]
> Your use-case is more like "When I create a user, I wanna make sure he's in the Auto Group unless I specify a more specific group." But the app shall only be active on creation, and not on group modification later on.

> Is this understanding correct?

Yes, that is my point.

**Comment by stjosh** [comment]
Fine. 👍🏻 I‘ll tackle this as soon as I find the time for it.

**Comment by fenvarien** [comment]
This feature would be perfect for my use-case as well. I really like this app and it's working nicely with my Nextcloud installations. But this tweak could be very helpful for some organizations like schools.

**Comment by stjosh** [comment]
See #51 - I'll work on this whenever I find some spare time in the coming days & weeks. 😉

**Comment by stjosh** [comment]
Somehow messed up the PR. See #53 now instead.

**Comment by stjosh** [comment]
I'll close this issue once I have published a new release 1.3.0. Things todo until then:

- [ ] update translations
- [ ] add changelog entry
- [ ] bump version number
- [ ] tag release

I haven't added the feature to also opt-out of group-deletion prevention, since this might create some unhandled edge-cases I don't want to take care of as long as no-one is asking specifically for this feature.

**Comment by stjosh** [comment]
Feature request has been implemented and released in app version 1.3.0

**Comment by fenvarien** [comment]
Thank you, that's great!
