### ISSUE TITLE
Should my "all users" group be selectable in "Group folder"'s share/ACL dialog?

### ISSUE THREAD

**Issue by nursoda** [stjosh/auto_groups#56]
I tried to save a file in a group folder but exclude it from most users. My idea: Add ACL to explicitely allow some key users (via their group) and disallow an "all users" group created manually and populated by "Auto Groups". Yet I am not even able to select the "all users" group in the ACL dialog at all, neither to allow nor to deny. Is that intended or a bug? I have the [same issue](https://github.com/icewind1991/group_everyone/issues/22) with the [Everyone](https://apps.nextcloud.com/apps/group_everyone) app.

I'm on NC21 and about to switch to 22 as soon as "Group Folders" is released.

**Comment by stjosh** [comment]
Hmm, not sure whether this really is an issue with those apps. I mean - the groups managed by AutoGroups are just regular groups. The only thing the app does is ensuring membership of all users.

So, unless you are able to select other groups _not_ managed by AutoGroups, I‘d say this is an issue with either the Group Folders app or the Nextcloud core. (And by „issue“, I don‘t even necessarily mean a bug - it could even be a use-case which is not supported for good reasons). A message in the Nextcloud suport forum might also help to clarify.

Feel free to re-open this issue once you have verified that you _can_ choose a group not managed by AutoGroups but you _cannot_ choose it anymore once added to AutoGroups.
