### ISSUE TITLE
Feature Request: Check only on Login

### ISSUE THREAD

**Issue by xbluemonkx** [stjosh/auto_groups#57]
At the moment there is a feature "only check on creation".

I would like to have the feature "only check on login" or "do not check on creation".

Background Info: We use the App "Registry" so that each user can create his own account. This account needs to be activated by the admin. So while the user can not log in, it gets assigend to the group "All members" when he created his account. Furthermore we do have a group chat that is shared with the group "All members". So as soon as a new member registers the group chat shows a message "User XY was added to the group chat" - even that user is not yet confirmed by the admin.

**Comment by xbluemonkx** [comment]
thinkin about this a little further: It would probably best to have a list of possible events, when the status should be checked and the user could check yes / no for each. would probably be much less confusing than an "yes check, but no. check only"

**Comment by stjosh** [comment]
Fiexed by #58 . Will publish a new Release 1.4.0 once the community had the chance to update the translations (i.e., roughly in a week or so).

**Comment by xbluemonkx** [comment]
amazing! thank you!

**Comment by stjosh** [comment]
Release v1.4.0 has been published

**Comment by xbluemonkx** [comment]
thank you very much! - will test this once my nextcloud has realised there is an update :)
