### ISSUE TITLE
Small Bug:   app.php deprcation error message

### ISSUE THREAD

**Issue by yupthatguy** [stjosh/auto_groups#61]
hey there,

just doing some maintenance, trying to clear my error log. I found this bug for your app:
{"reqId":"Yp5kRCRvIDQU4afxJvGeLgAAURY","level":0,"time":"June 06, 2022 20:32:04","remoteAddr":"192.168.61.1","user":"fathertimetest","app":"auto_groups","method":"PUT","url":"/index.php/apps/user_status/heartbeat","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.64 Safari/537.36","version":"24.0.1.1"}

I am on NC24, Ubuntu 20.04, php7.4-fpm

**Comment by stjosh** [comment]
Thanks for reporting, I'll tackle this in the next release

**Comment by stjosh** [comment]
Fixed in Release 1.5.0
