### ISSUE TITLE
SSO & SAML authentication new accounts in group do not see files shared with group

### ISSUE THREAD

**Issue by outofcontrol** [stjosh/auto_groups#63]
This issue is a bit different than https://github.com/stjosh/auto_groups/issues/42. Our SAML users do get the correct member group, but, the new SAML member in the group can't see any of the folders and files that are shared with that group. 

If I either:
- remove the user from the group and re-add them
- or if I delete the share and reset it
then the new SAML user sees all the shares. 

Manually added users added to the group also immediately see all the shares. 

Is it possible there is an event that is not correctly triggered for these new SAML users? This is a bit of a show stopper for using this plugin, though I don't know of an alternative. 

Happy to help test this if you have some suggested debugging ideas. 

Edit: Logging out and back in, no change. My settings for the plugin are:

<img width="776" alt="ooc-screenshot 2" src="https://user-images.githubusercontent.com/69415/193945189-19318c2d-daec-43ec-b2e9-9d964c195a50.png">

**Comment by outofcontrol** [comment]
Okay, a little more info. The folders are shared, but are under Shares -> Pending Shares, and the user needs to Accept each share. Is there a way to force the shares to be accepted automatically? If yes, perhaps an option to enable/disable 'Auto accept pending shares?'

**Comment by stjosh** [comment]
Hi @outofcontrol , many thanks for getting in touch!

First of all, it is _very_ interesting to hear that SAML/SSO is now working with the `auto_groups` app - I will ask you for more details about your configuration/versions in #42 .

Regarding your remaining issue, it seems that unfortunately, this is not specific to `auto_groups`, but also for LDAP-users which are automatically assigned to Nextcloud groups. See, e.g., https://github.com/nextcloud/server/issues/25062#issuecomment-864243249 . 

There seems to be a manual workaround by setting a DB trigger - maybe this could be a "solution" for you? However, of course, this is a bit dangerous as the DB schema etc. might change. https://github.com/nextcloud/server/issues/25062#issuecomment-856459649 

Furthermore, have you tried the config options documented [here](https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/config_sample_php_parameters.html#sharing)? Specifically, there are some options regarding `share_accept`.

Pls let me know about your progress.

**Comment by stjosh** [comment]
Hi @outofcontrol, may I ask you for your feedback once again? Many thanks.

**Comment by KhronosWebservices** [comment]
Yes, apologies on the long delay. Crazy work summer/fall. Yes, auto_groups works fine with our SAML setup :) No idea how I managed that.

In the end I switched to Group Folders which works fine. Also in part due to the size of the shared folder needed a separate volume to be stored on. 

If I remember correct, I did try the config options, without success.

**Comment by stjosh** [comment]
Many thanks for your feedback @KhronosWebservices ! Glad you have found a setup which is working for you! 👍🏻 

Very interesting you got it to run with SAML - maybe that other issue has been fixed meanwhile?

I will close this issue, as it is most probably not specific to this app and there's nothing I can directly do about this.
