### ISSUE TITLE
Clicking the admin checkbox "Check ...on every login" makes the config panel disappear

### ISSUE THREAD

**Issue by Mer0me** [stjosh/auto_groups#65]
I've just installed the app for the first time on NC25.0.2.
When I click on the last checkbox of the app config, the main container of Nextcloud simply disappear !

It seems to be this container :

`<main id="content" class="app-setting">`

**Comment by stjosh** [comment]
Hi @Mer0me 
Thanks for getting in touch. I can't reproduce your issue in my own NC25.0.2 install. Could you please provide additional details? (Browser, Screenshots)?

**Comment by Mer0me** [comment]
I'm on Firefox 102.5 ESR.
The problem does not occur on Chrome.

Here is a capture of the symptom :

![bugautogroup](https://user-images.githubusercontent.com/6248852/209347697-127c0854-e677-445c-9657-c5ea897be480.gif)

**Comment by stjosh** [comment]
Hi @Mer0me 

Thanks for the report - I can now kind of reproduce this behavior indeed. I.e., it looks a bit different on my end, but the strange effect that things are disappearing is the same. Interestingly, it only happens on my end if the "Quota Warnings" App is active as well.

I have the impression that this is an effect of the NC 25 design update in combination with the settings template... Will have to investigate further, though.

**Comment by stjosh** [comment]
Seems that adding a simple `position: relative;` to my top-level settings container fixes the issue (see 54e053a). I have just published v1.5.1 with this fix.

Feel free to re-open the issue, should it still persist on your end.
