### ISSUE TITLE
Auto Group does not work with LDAP user backend

### ISSUE THREAD

**Issue by Mer0me** [stjosh/auto_groups#66]
I manage 2 instances of Nextcloud. One is using Nextcloud user backend, the other is using LDAP (Active Directory) backend.

On the Active Directory LDAP users backend, users are not added to auto group, never. Nothing happens even if I check the last box "Check for correct auto group membership on every login" and I connect with a LDAP user.

On the Nextcloud instance with regular user backend, with the very same configuration, it works : when a user is connected, it is added to the auto group I've defined.

Does this app supposed to work with LDAP user backend ?

**Comment by stjosh** [comment]
Hi @Mer0me 

Good question! I *think* it has worked with LDAP some Nextcloud releases ago. However, as I do not have an LDAP installation to test this app with, this is actually not considered a fully supported setup.

This app works by subscribing to Nextcloud events like `UserLoggedInEvent`. If the LDAP app does not emit this event, there's not much I can do about it. The "Chck on every login" setting would be needed for sure, but maybe the LDAP app changed its behavior to not send the "LoggedIn"-Event anymore?

Unfortunately, I currently don't have much time to dig deeper into this issue.

**Comment by citronalco** [comment]
I can confirm auto_groups does work properly with LDAP and NC 27. Users get added, no problems.
"Check on every login" is enabled.

**Comment by stjosh** [comment]
Thanks for your feedback, closed.
