### ISSUE TITLE
 Error: This app cannot be enabled because it makes the server unstable 

### ISSUE THREAD

**Issue by CorneAussems** [stjosh/auto_groups#68]
Installed 1.5.2 on my Nextcloud 25.0.4 

 Error: This app cannot be enabled because it makes the server unstable

**Comment by stjosh** [comment]
Hi @CorneAussems , thanks for getting in touch. Actually, I am running this app successfully on my own Nextcloud 25 installation (25.0.8). Furthermore, the daily build also tests app compatibility down to Nextcloud 21. Therefore, I am pretty sure that there is not a fundamental incompatibility between Nextcloud 25 and the auto_groups app.

Could you therefore provide some more context? Screenshots and logs could probably help to narrow down the issue.

**Comment by stjosh** [comment]
Closed due to missing feedback.
